#!/usr/bin/env python3
""" List all databases in MongoDB """
import pymongo


def list_all_databases(mongo_client):
    """ List all databases in MongoDB """
    return mongo_client.list_database_names()
